#ifndef WIFI_NETWORK_CONFIG_H
#define WIFI_NETWORK_CONFIG_H

#include "esp_wifi_types.h"
// Features

#define WIFI_NETWORK_USE_LED 1
#define WIFI_NETWORK_USE_BUTTON 1
#define WIFI_NETWORK_DEBUG_LOG 1
#define WIFI_NETWORK_CUSTOM_ERROR_CHECK 0
#define WIFI_NETWORK_SAVE_INFO 1
// Configurations

#define WIFI_NETWORK_DEFAULT_STA_SSID "MonsterHotspot"
#define WIFI_NETWORK_DEFAULT_STA_PASS "12345678"
#define WIFI_NETWORK_DEFAULT_AP_SSID "WifiNetworkAP"
#define WIFI_NETWORK_DEFAULT_AP_PASS "12345678"
#define WIFI_NETWORK_DEFAULT_AP_CHANNEL 1
#define WIFI_NETWORK_DEFAULT_AP_MAX_STA_CONN 4
#define WIFI_NETWORK_DEFAULT_AP_AUTH_MODE WIFI_AUTH_WPA_WPA2_PSK
#define WIFI_NETWORK_DEFAULT_MIN_SCAN_TIME 100
#define WIFI_NETWORK_DEFAULT_MAX_SCAN_TIME 500

#define WIFI_NETWORK_AP_PASSWORD_MUST_HAVE 1
#define WIFI_NETWORK_AP_SSID_MUST_HAVE 0
// Limits and Constants 
#define WIFI_NETWORK_MAX_SSID_LEN 32
#define WIFI_NETWORK_MAX_PASS_LEN 64 

#endif // WIFI_NETWORK_CONFIG_H